module.exports = {
    defaultSeverity: 'warning',
    extends: ['tslint:recommended'],
    rules: {
        'adjacent-overload-signatures': true,
        'member-access': [true, 'no-public'],
        'member-ordering': [
            true,
            {
                order: 'statics-first',
            },
        ],
        'no-any': false,
        'no-empty-interface': false,
        'no-import-side-effect': true,
        'no-internal-module': true,
        'no-magic-numbers': false,
        'no-namespace': true,
        'no-var-requires': true,
        'prefer-for-of': true,
        'unified-signatures': true,
        'await-promise': true,
        'curly': true,
        'forin': false,
        'no-async-without-await': true,
        'no-construct': true,
        'no-duplicate-super': true,
        'no-duplicate-switch-case': true,
        'no-duplicate-imports': true,
        'no-duplicate-variable': true,
        'no-floating-promises': true,
        'no-inferred-empty-object-type': false,
        'no-invalid-template-strings': true,
        'no-misused-new': true,
        'no-return-await': true,
        'no-shadowed-variable': true,
        'no-string-literal': true,
        'no-string-throw': true,
        'no-unsafe-any': false,
        'no-unsafe-finally': true,
        'no-var-keyword': true,
        'prefer-conditional-expression': true,
        'prefer-object-spread': true,
        'restrict-plus-operands': true,
        'triple-equals': true,
        'invalid-void': true,
        'object-literal-sort-keys': {
            options: 'match-declaration-order-only',
        },
        'prefer-const': true,
        'prefer-readonly': true,
        'array-type': [true, 'array-simple'],
        'arrow-return-shorthand': true,
        'binary-expression-operand-order': true,
        'class-name': true,
        'interface-name': [true, 'never-prefix'],
        'interface-over-type-literal': true,
        'no-angle-bracket-type-assertion': true,
        'no-boolean-literal-compare': true,
        'no-redundant-jsdoc': true,
        'no-unnecessary-qualifier': true,
        'object-literal-key-quotes': [true, 'consistent-as-needed'],
        'object-literal-shorthand': true,
        'ordered-imports': [
            true,
            {
                'import-sources-order': 'lowercase-first',
                'named-imports-order': 'lowercase-first',
                'grouped-imports': true,
                'module-source-path': 'full',
            },
        ],
        'prefer-method-signature': true,
        'prefer-switch': true,
        'prefer-template': [true, 'allow-single-concat'],
        'prefer-while': true,
        'space-within-parens': true,
        'switch-final-break': true,
        'type-literal-delimiter': true,
        'unnecessary-else': true,
        'arrow-parens': true,
        'number-literal-format': true,
        'quotemark': [true, 'single'],
        'semicolon': [true, 'always'],
        'no-irregular-whitespace': true,
        'no-trailing-whitespace': true,
        'new-parens': true,
        'import-spacing': true,
        'eofline': true,
        'trailing-comma': true,

        'no-console': false,
    },
    rulesDirectory: [],
};
